[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
version = "0.0.0"
edition = "2024"
authors = ["yaolei313@gmail.com"]

[workspace.dependencies]
# local crates
lib-auth = { path = "crates/lib-auth", version = "0.0.0" }
lib-utils = { path = "crates/lib-utils", version = "0.0.0" }
lib-core = { path = "crates/lib-core", version = "0.0.0" }
# other crates
anyhow = "1.0.79"
axum = "0.7.4"
axum-extra = { version = "0.9.2", features = ["typed-header"] }
chrono = { version = "0.4.40", features = ["serde"] }
dotenv = "0.15.0"
features = "0.10.0"
headers = "0.4.0"
jsonwebtoken = "9.3.1"
runtime-tokio = "0.0.0"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.112"
sqlx = { version = "0.7.3", features = ["runtime-tokio", "postgres", "chrono", "uuid"] }
tokio = { version = "1.35.1", features = ["full"] }
tower = { version = "0.4.13", features = [
    "util",
    "timeout",
    "limit",
    "load-shed",
    "steer",
    "filter",
] }
tower-http = { version = "0.5.1", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
uuid = "1.16.0"
validator = { version = "0.20.0", features = ["derive"] }
async-trait = "0.1.88"
log = "0.4"