[[login.keys]]
kid = "v1"
private_key_path = "config/private_key1.pem"
public_key_path = "config/public_key1.pem"


[[login.keys]]
kid = "v2"
private_key_path = "config/private_key2.pem"
public_key_path = "config/public_key2.pem"

[[mfa.keys]]
kid = "mv1"
private_key_path = "config/private_key3.pem"
public_key_path = "config/public_key3.pem"


[[mfa.keys]]
kid = "mv2"
private_key_path = "config/private_key4.pem"
public_key_path = "config/public_key4.pem"