[server]
host = "0.0.0.0"
port = 8080
worker_id = 1

[database]
min_connections = 5
max_connections = 20
idle_timeout_seconds = 30

[redis]
url = "redis://127.0.0.1:6379"

[jwt]
issuer = "https://accounts.share-stars.com"
audience = "https://www.share-stars.com/api"
expire_seconds = 3600

[sms]
account_sid = ""
auth_token = ""
from_phone = ""
status_callback_url = ""


