[server]
port = 8080
host = "0.0.0.0"

[database]
min_connections = 5
max_connections = 20
idle_timeout_seconds = 30

[jwt]
issuer = "yao"
expire_seconds = 3600

[[jwt.keys]]
kid = "v1"
private_key_path = "config/private_key1.pem"
public_key_path = "config/public_key1.pem"


[[jwt.keys]]
kid = "v2"
private_key_path = "config/private_key2.pem"
public_key_path = "config/public_key2.pem"

[sms]
url = ""
account_sid = ""
auth_token = ""
status_callback_url = ""


