[package]
name = "biz-store"
version.workspace = true
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
features = "0.10.0"
runtime-tokio = "0.0.0"
sqlx = "0.7.3"
